### ISSUE TITLE
GitHub repositories labels

### ISSUE THREAD

**Issue by alexis-** [supermemo-wiki/Issues#1]
Please help standardizing labels across repositories. It's still messy.
E.g. some repositories use `++` while other use `enhancement`, some have `UI` but some don't.

Specific needs:
- Change `tech` description to the more general "Technical task (code improvement)"

Notes:
- Use https://github.com/organizations/supermemo/settings/labels to set default labels for all repositories
- http://www.dorukdestan.com/github-label-manager/# might help with copying labels across repositories

**Comment by alexis-** [comment]
@dumbyme @nikedinikedi help !

**Comment by dumbyme** [comment]
@alexis- please review the labels I have created.

**Comment by alexis-** [comment]
- Priorities: Possibly make the label shorter (e.g. `pri-1`, `pri-2`, ...)
- `candidate`: This can already be handled with Milestones
- `feature-request`: Seem like duplicate since an issue will be `under-review` by default, and can then only transition toward either , `enhancement`, or `bug`. Also adds another step which I'm not sure is necessary at this stage. What is the rationale for it ?
- `under-review`:
1) I would prefer it if there was a solution to create a search filter by subtracting all issues that aren't `enhancement`, or `bug`. Rationale: No labeling action required ; Avoid adding more labels
2) If (1) isn't possible, I would be OK with this if it can be assigned by default to an issue

Very good job. I like that you have identified situations that had not been considered until now.

**Comment by alexis-** [comment]
Once we settle on which labels to use, there still remain the very cumbersome work of deploying them on all the repositories (semi-?)manually.

Keep in mind that different repositories have specific label requirements (e.g. `github`, `community`, `video`, `research` for this one)

**Comment by alexis-** [comment]
I have created a Sandbox for all our experimentations : https://github.com/supermemo/Sandbox

You have full admin permissions on this repo, feel free to try even the most crazy stuffs.
