### ISSUE TITLE
Curate a list of resources (Awesome)

### ISSUE THREAD

**Issue by alessivs** [supermemo-wiki/Issues#20]
* Create a curated, succinct, categorized listing of linked resources related to SuperMemo, perhaps in the form of an **[Awesome](https://github.com/sindresorhus/awesome) SuperMemo**. 
* (Opinion) I believe members of @SuperMemo are in a good position for this undertaking.
* Keep it on GitHub so others can possibly add to it via familiar mechanisms (PRs / issues).

**Comment by alexis-** [comment]
This is a great idea. *Awesome* lists are a very efficient mean of indexing small scale resources.

Would you like to submit a PR to kick it off ?

**Comment by alexis-** [comment]
https://github.com/supermemo/awesome-supermemo
